In [ ]:
## vector 1d


In [2]:
import numpy as np

In [3]:
simple_list=[0,1,2,3]
np.array(simple_list)

array([0, 1, 2, 3])

In [4]:
arr=np.array([5,6])
arr

array([5, 6])

In [5]:
list_of_list=[1,2,3],[4,5,6],[7,8,9]
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(5,23)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22])

In [11]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones((5,),dtype=int)

array([1, 1, 1, 1, 1])

In [14]:
np.ones(5,)

array([1., 1., 1., 1., 1.])

In [15]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [16]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
np.random.rand(2,5)

array([[0.99515082, 0.42726781, 0.18749203, 0.61550181, 0.06643489],
       [0.33496321, 0.7833491 , 0.77096762, 0.88054683, 0.70033305]])

In [18]:
np.random.randint(2,3)

2

In [19]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
sample_array.min()

2

In [21]:
sample_array.max()

19

In [22]:
sample_array.argmax()

17

In [23]:
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
sample_array.dtype

dtype('int64')

In [26]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
sample_array[4:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
sample_array[1]=100
sample_array

array([  2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19])

In [30]:
sample_array=np.arange(2,5)
sample_array

array([2, 3, 4])

In [32]:
## Two Dimensional Array
sample_matrix=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
sample_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
sample_matrix[0][2]

3

In [34]:
sample_matrix[:][2]

array([ 9, 10, 11, 12])

In [35]:
np.log(sample_array)

array([0.69314718, 1.09861229, 1.38629436])

In [36]:
np.sqrt(sample_matrix)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [37]:
np.exp(sample_array)

array([ 7.3890561 , 20.08553692, 54.59815003])

In [38]:
np.std(sample_array)

0.816496580927726

In [39]:
np.square(sample_array)

array([ 4,  9, 16])

In [40]:
np.var(sample_array)

0.6666666666666666

In [41]:
np.argmin(sample_array)

0

In [42]:
np.argmax(sample_array)

2

In [43]:
np.mean(sample_array)

3.0